name: BungeeSkywarsFFA
version: '${project.version}'
main: me.lara.bungeeskywarsffa.BungeeSkywarsFFA
api-version: 1.19
authors: [ Timeox2k ]
commands:
  setup:
  stats:
  killstreak:
    aliases: [ks, streak, kills]